@startuml

ProgrammeProviderSource <|..left- ProgrammeSource

MediaSessionCompat.Callback <|.. MediaSessionCallback

Playback <|.. RemotePlayBack

ProgrammeProvider --> ProgrammeProviderSource : 获取MediaMetadata

QueueManager --> ProgrammeProvider : 获取数据

PlaybackManager --> QueueManager : 存放可播放的音频\n以及当前播放的POS

PlaybackManager --> PlaybackServiceCallback : Manager的Service回调

PlaybackManager --> MediaSessionCallback : 接收受控端回调

PlaybackManager --> RemotePlayBack : 音频播放接口

@enduml